name: Release

on:
  push:
    tags: *
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller
      - name: Build
        run: pyinstaller --onefile --console nvgtpkg.py
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/nvgtpkg.exe